# <Build step #1: build the React frontend>
# pull the official Node docker image
FROM node:16-alpine as builder

# set a working directory
WORKDIR /frontend

# copy the package dependencies file
COPY package*.json /frontend

# install dependencies
RUN npm install

# copy remaining codes
COPY . /frontend

# build the project for production
RUN npm run build

# <Build step #2: build a Nginx container>
# pull the official Nginx docker image
FROM nginx

# copy the nginx.conf file from the docker host to the docker container
COPY nginx.conf /etc/nginx/conf.d/default.conf

# copy production build files from builder phase to nginx
COPY --from=builder /frontend/build /usr/share/nginx/html

# run nginx in foreground
CMD ["nginx", "-g", "daemon off;"]