version: '3.9'

services:
  ###########################
  #   backend container
  ###########################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.api.server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # hostPath:containerPath:mode
      - ./backend:/backend:consistent
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000'

  ###########################
  #   frontend container
  ###########################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    environment:
      - WATCHPACK_POLLING=true
    command: npm run start
    volumes:
      # hostPath:containerPath:mode
      - ./frontend:/frontend:consistent
    ports:
      - '3000:3000'
